#!/usr/bin/python
# A little wrapper around pycco, to add Rust support.
import pycco
from pygments import lexers, formatters
import re
pycco.main.languages[".rs"] = { "name": "rust", "symbol": "//"}

# need to re-build this stuff...
for ext, l in pycco.main.languages.items():
    # Does the line begin with a comment?
    l["comment_matcher"] = re.compile(r"^\s*" + l["symbol"] + "\s?")
    # The dividing token we feed into Pygments, to delimit the boundaries between
    # sections.
    l["divider_text"] = "\n" + l["symbol"] + "DIVIDER\n"
    # The mirror of `divider_text` that we expect Pygments to return. We can split
    # on this to recover the original sections.
    l["divider_html"] = re.compile(r'\n*<span class="c[1]?">' + l["symbol"] + 'DIVIDER</span>\n*')
    # Get the Pygments Lexer for this language.
    l["lexer"] = lexers.get_lexer_by_name(l["name"])

pycco.main.main()
